export enum trainingRoutes {
  main = 'main',
  test = 'test',
  paths = 'paths',
  selectedPath = 'selected-path',
  program = 'program',
  roadmap = 'roadmap',
  course = 'course',
  leason = 'leason',
  leasonTest = 'leason-test',
  certificate = 'certificate',
  pdf = 'pdf',
  endCourse = 'end-course',
  finalTest = 'final-test',
  testPartTwo = 'test-part-two',
  skillsLibrary = 'skills-library',
  allSkillsLibrary = 'all-skills-library',
  onlineCourses = 'online-courses',
  trainingPaths = 'training-paths',
  courseDetails='course-details',
  courseschedule='course-schedule',
  courseRating='course-rating',
  courseInstructor='course-instructor',
  courseGeneralInfo='course-general-info',
  cart='cart'
}
