export enum servicesRoutes {
main='main',
servicesAdvisors='services-advisors',
servicesSocial='services-social',
servicesTest='services-test',
chooseAdvisor='choose-advisor',
TypesOfConsultations='types-of-consultations',
TextConsultation='text-consultation',
OnlineConsultation='online-consultation',
biography='biography',
localcertificate='local-certificate',
internationalCertificate='international-certificate',
certificateDetails='certificate-details',
advisor='advisor',
submitAdvisor='submit-advisor',
addArticle = 'add-article',
}